Add runbook and update codeowners
Financial-Times/publish-carousel pull request #52
Opened 2021-01-26 12:18 UTC by bboykov

2021-01-27 14:11 UTC, ekaneva requested changes

2021-01-27 14:11 UTC, ekaneva commented on runbooks/runbook.md
> +The service is deployed in both Delivery clusters. The failover guide for the cluster is located here: <https://github.com/Financial-Times/upp-docs/tree/master/failover-guides/delivery-cluster>
Those are not correct, Publish history is not deployed on the Delivery nor any of our other clusters.
Maybe @georgi-denchew could be able to explain better how to change these sections.

2021-01-27 14:34 UTC, ekaneva requested changes

2021-01-27 14:34 UTC, ekaneva commented on runbooks/runbook.md
> +The service is deployed in both Delivery clusters. The failover guide for the cluster is located here: <https://github.com/Financial-Times/upp-docs/tree/master/failover-guides/delivery-cluster>
Publish Carousel is deployed in the Publishing clusters, so please update Architecture Type and Failover docs accordingly.

2021-01-27 14:34 UTC, ekaneva commented on runbooks/runbook.md
> +- <https://upp-prod-delivery-us.upp.ft.com/__health/>
Publishing cluster.

2021-01-27 14:39 UTC, bboykov commented on runbooks/runbook.md
> +The service is deployed in both Delivery clusters. The failover guide for the cluster is located here: <https://github.com/Financial-Times/upp-docs/tree/master/failover-guides/delivery-cluster>
👍

2021-01-27 14:39 UTC, bboykov commented on runbooks/runbook.md
> +- <https://upp-prod-delivery-us.upp.ft.com/__health/>
👍

2021-01-27 14:49 UTC, ekaneva requested changes

2021-01-27 14:49 UTC, ekaneva commented on runbooks/runbook.md
> +The service is deployed in both clusters. The failover guide for the cluster is located here: <https://github.com/Financial-Times/upp-docs/tree/master/failover-guides/publishing-cluster>
```suggestion
The service is deployed in both Publishing clusters. The failover guide for the cluster is located here: <https://github.com/Financial-Times/upp-docs/tree/master/failover-guides/publishing-cluster>
```

2021-01-27 14:49 UTC, ekaneva commented on runbooks/runbook.md
> +ActiveActive
```suggestion
ActivePassive
```

2021-01-27 15:16 UTC, ekaneva submitted a review, later dismissed

2021-01-28 11:30 UTC, MiroslavGatsanoga commented on runbooks/runbook.md
> +- <https://upp-prod-publish-eu.upp.ft.com/__health/>
Those should be the service health endpoints:
https://upp-prod-publish-eu.upp.ft.com/__health/__pods-health?service-name=publish-carousel
https://upp-prod-publish-us.upp.ft.com/__health/__pods-health?service-name=publish-carousel

2021-01-28 11:36 UTC, MiroslavGatsanoga submitted a review, later dismissed

2021-01-28 11:36 UTC, ekaneva requested changes

2021-01-28 11:36 UTC, ekaneva commented on runbooks/runbook.md
> +
In that case, this sentence is redundant:
```suggestion
```

2021-01-28 11:38 UTC, ekaneva approved these changes
Looks good to me, just squash the commits once you're done.

2021-01-28 11:40 UTC, MiroslavGatsanoga approved these changes

2021-01-28 11:42 UTC, merged